### PR TITLE
Add Google Oauth flow intergration

### PR DESCRIPTION
**Pull request by phuclh**
## What changed?

I added Google Oauth flow to this package, so users can authorize our app to get the access token from their Google account. The access token can be saved under `Key Eloquent Model` or `JSON file`.

I also changed a lot of things in the `GoogleApiServiceProvider`. Below is why I did that:

Currently, we are running a query to find the Key model and call the Google Service to check if the access token has expired, then refresh it and update it back to the database. In my opnion,  this is an expensive cost. We have to repeat those steps on every request even we don't use any Google services on that route. If Google Service is slow, it also slows down our app.

We better have each Google service in its own package. That means this `laravel-google-api` package will take responsibility for getting and saving the access token. Services package will take that access token and expose nice API methods for us.

For instance, when working on the SEO package, I installed the `laravel-google-api` to get the access token and `laravel-google-console` to check the keyword volumes.

```
// Get access token from Google Oauth package.
$accessToken = GoogleOauth::accessToken('google-console');

// Check keyword volumes
GoogleConsole::setAccessToken($accessToken)->checkKeywordVolumes();
```

Screen Shot 2021-04-21 at 12 26 09 AM

Moreover, if doing this way, we not only use our services package, but also we can use 3rd packages. Something like this: https://github.com/schulzefelix/laravel-search-console

### Authorization

To set up the Google Oauth flow, we just add `GoogleOauth::routes()` from GoogleOauth Facade in `web.php`

That will create 3 routes:

```
Route::group([
    'prefix'     => $prefix,
    'middleware' => $middleware,
], function () {
    Route::get('oauth', [GoogleOauthController::class, 'redirect'])->name('google-oauth.connect');
    Route::get('callback', [GoogleOauthController::class, 'handleCallback'])->name('google-oauth.callback');
    Route::get('logout', [GoogleOauthController::class, 'logout'])->name('google-oauth.logout');
});
```

We can custom the `$prefix` and `$middleware` like this: 

`GoogleOauth::routes('customer-prefiix', ['web', 'nova', 'api']);`.

Then create an anchor or button in the front-end.

```
$url = route('google-oauth.connect', [
    'identifier' => 'google-console', // The unique key for each service package.
    'home_url'   => url('google-oauth/get'), // The url you want to redirect back after the Oauth flow done.
    'scopes'     => [
        Google_Service_SearchConsole::WEBMASTERS_READONLY
    ] // Array of scopes that we want to request from user.
]);

return '<a href="' . $url . '">Connect to Google</a>';
```

Screen Shot 2021-04-21 at 12 35 40 AM

### Get the access token

```
$accessToken = GoogleOauth::accessToken('google-console');
```

or 

```
$accessToken = GoogleOauth::setIdentifier('google-console')->accessToken();
```

`Identifier` is a unique key for each service package.

The `accessToken` method will refresh the access token automatically if it has expired.

```
$accessToken->getAccessToken(); // Return a string of access token.
$accessToken->getRefreshToken(); // Return refresh token.
$accessToken->hasExpires(); // Check if the access token has expired or not.
```

## Google Oauth Drivers

Currently, this package supports 2 drivers which are:

- `JsonDriver`: Saving and getting access token via a JSON file.
- `KeyEloquentDriver`: Saving and getting access token via the Key model.

The package uses `JsonDriver` by default, we can override it by adding this in the `boot` method of `AppServiceProvider`

```
public function boot()
{
    GoogleOauth::useDriver(KeyEloquentDriver::class);
}
```

We also can write a custom driver. The custom driver class must implement `GoogleOauthDriver` interface and use the above `useDriver` method to register the customer driver.

Screen Shot 2021-04-21 at 12 44 50 AM

### CODE REVIEW

**Comment by drewroberts** [comment]
I think the only thing I have been saving in that Keys model is the access token from the Google response.

**Comment by drewroberts** [comment]
Can we add to the config of this package all of the permissions that will be needed with the token?

@kylebarney Can you review this PR and let me know your thoughts?

**Comment by drewroberts** [comment]
> To set up the Google Oauth flow, we just add GoogleOauth::routes() from GoogleOauth Facade in web.php

I would rather register the routes from the package. @pdbreen Could you help with this?

**Comment by pdbreen** [comment]
https://github.com/tipoff/laravel-google-api/pull/37

**Comment by drewroberts** [comment]
@phuclh I like the json driver option, but how would that work with multiple accounts? How are those being named?

**Comment by joshtorres** [comment]
I do agree that's an expensive cost to run a check for an expired token on every request for every service. However, I'm not sure if we need separate packages for each Google Service, as I think it may complicate the development experience quite a bit. What if we just put in the config which services we want to enable, and it only checks those?
Also, here are two ways I've handled expired API tokens in the past:
1) Refresh if expired 
- try to use the API key in a request
- if API returns a token expired response, then refresh the key and re-run the query again.
- save it into the cache so subsequent requests don't refresh the key again.
**OR**
2) We could check whatever API keys we want to check once on the application load, and save them into the cache and then use those on subsequent requests without checking again.

What do you guys think about those options?

**Comment by phuclh** [comment]
> @phuclh I like the json driver option, but how would that work with multiple accounts? How are those being named?

@drewroberts When creating a URL for the user to click to authorize permission, you can pass the `identifier` parameter.

```
$url = route('google-oauth.connect', [
    'identifier' => 'google-console', // The unique key for each service package.
    'home_url'   => url('google-oauth/get'), // The url you want to redirect back after the Oauth flow done.
    'scopes'     => [
        Google_Service_SearchConsole::WEBMASTERS_READONLY
    ] // Array of scopes that we want to request from user.
]);
```

In this case, the JSON file name will be `google-console`. If the file exsits, the package will update the access token, if not it will create a new file.

And we can pull the access token with the `identifier`.

`$accessToken = GoogleOauth::accessToken('google-console');`

**Comment by phuclh** [comment]
> I do agree that's an expensive cost to run a check for an expired token on every request for every service. However, I'm not sure if we need separate packages for each Google Service, as I think it may complicate the development experience quite a bit. What if we just put in the config which services we want to enable, and it only checks those?
> Also, here are two ways I've handled expired API tokens in the past:
> 
> 1. Refresh if expired
> 
> * try to use the API key in a request
> * if API returns a token expired response, then refresh the key and re-run the query again.
> * save it into the cache so subsequent requests don't refresh the key again.
>   **OR**
> 
> 1. We could check whatever API keys we want to check once on the application load, and save them into the cache and then use those on subsequent requests without checking again.
> 
> What do you guys think about those options?

@joshtorres Currently, whenever you pull the access token from `GoogleOauth::accessToken()`, it will auto-refresh the token if the token has expired. It means, you only refresh the token whenever you need it and actually use it :D.

**Review by drewroberts — APPROVED** [review]
Thank you! ☀️

**Pull request merged**
